package GUI;

import Interfaces.BasketInterface;
import Interfaces.ItemInterface;
import Interfaces.SerializationInterface;
import Interfaces.SummaryInterface;
import javax.swing.JFileChooser;

/**
 *
 * @author tomwi
 */
public class ButtonPanel extends javax.swing.JPanel{

    /**
     * Creates new form ButtonPanel
     */
    public ButtonPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(60, 0), new java.awt.Dimension(60, 0), new java.awt.Dimension(60, 32767));
        addChairButton = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        addTableButton = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        addDeskButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        loadBasketButton = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        saveBasketButton = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        clearBasketButton = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        totalPriceButton = new javax.swing.JButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        showSummaryButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(57, 124, 213));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setPreferredSize(new java.awt.Dimension(500, 200));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));
        add(filler9);

        addChairButton.setText("Add Chair");
        addChairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChairButtonActionPerformed(evt);
            }
        });
        add(addChairButton);
        add(filler4);

        addTableButton.setText("Add Table");
        addTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTableButtonActionPerformed(evt);
            }
        });
        add(addTableButton);
        add(filler5);

        addDeskButton.setText("Add Desk");
        addDeskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDeskButtonActionPerformed(evt);
            }
        });
        add(addDeskButton);
        add(filler1);

        loadBasketButton.setText("Load Basket");
        loadBasketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBasketButtonActionPerformed(evt);
            }
        });
        add(loadBasketButton);
        add(filler6);

        saveBasketButton.setText("Save Basket");
        saveBasketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBasketButtonActionPerformed(evt);
            }
        });
        add(saveBasketButton);
        add(filler7);

        clearBasketButton.setBackground(new java.awt.Color(255, 0, 0));
        clearBasketButton.setText("Clear Basket");
        clearBasketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBasketButtonActionPerformed(evt);
            }
        });
        add(clearBasketButton);
        add(filler2);

        totalPriceButton.setText("Total Price of Basket");
        totalPriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPriceButtonActionPerformed(evt);
            }
        });
        add(totalPriceButton);
        add(filler8);

        showSummaryButton.setText("Show Summary");
        showSummaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSummaryButtonActionPerformed(evt);
            }
        });
        add(showSummaryButton);
    }// </editor-fold>//GEN-END:initComponents

    private void addChairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChairButtonActionPerformed
        
        itemListener.newChairPanel();
    }//GEN-LAST:event_addChairButtonActionPerformed

    private void addTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTableButtonActionPerformed
        
        itemListener.newTablePanel();
    }//GEN-LAST:event_addTableButtonActionPerformed

    private void addDeskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDeskButtonActionPerformed

        itemListener.newDeskPanel();
    }//GEN-LAST:event_addDeskButtonActionPerformed

    private void showSummaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSummaryButtonActionPerformed
        
        summaryListener.showBasketSummary();
        
    }//GEN-LAST:event_showSummaryButtonActionPerformed

    private void clearBasketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBasketButtonActionPerformed
        
        basketListener.removeAllItemsFromBasket();
    }//GEN-LAST:event_clearBasketButtonActionPerformed

    private void totalPriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPriceButtonActionPerformed
        
        itemListener.totalPricePanel();
    }//GEN-LAST:event_totalPriceButtonActionPerformed

    private void loadBasketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBasketButtonActionPerformed
        
        int choice = 0;
        JFileChooser file = new JFileChooser();
        choice = file.showOpenDialog(this);
        if (choice == JFileChooser.APPROVE_OPTION){
            serializeListener.loadBasket(file.getSelectedFile());            
        }    
    }//GEN-LAST:event_loadBasketButtonActionPerformed

    private void saveBasketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBasketButtonActionPerformed
        int choice = 0;
        JFileChooser file = new JFileChooser();
        choice = file.showSaveDialog(this);
        if (choice == JFileChooser.APPROVE_OPTION){
            serializeListener.saveBasket(file.getSelectedFile());
        }
    }//GEN-LAST:event_saveBasketButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addChairButton;
    private javax.swing.JButton addDeskButton;
    private javax.swing.JButton addTableButton;
    private javax.swing.JButton clearBasketButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton loadBasketButton;
    private javax.swing.JButton saveBasketButton;
    private javax.swing.JButton showSummaryButton;
    private javax.swing.JButton totalPriceButton;
    // End of variables declaration//GEN-END:variables

    private ItemInterface itemListener;
    private BasketInterface basketListener;
    private SummaryInterface summaryListener;
    private SerializationInterface serializeListener;

    
    
    public void addItemlListener(ItemInterface listener) {
        this.itemListener = listener;
    }
    
    public void addBasketListener(BasketInterface listener) {
        this.basketListener = listener;
    }
    
    public void addSummaryListener(SummaryInterface listener) {
        this.summaryListener = listener;
    }    
    
    public void setSerializeListener(SerializationInterface listener){
        this.serializeListener = listener;
    }
}
