package GUI;

//
import Items.*;
import Interfaces.NewItemInterface;
import javax.swing.JOptionPane;

/**
 *
 * @author tomwi
 */
public class ChairPanel extends javax.swing.JPanel {

    private final NewItemInterface newItemInterface;
    private Chair chair;

    /**
     * Creates new form orderItemPanel
     *
     * @param newItemInterface
     */
    public ChairPanel(NewItemInterface newItemInterface) {
        initComponents();
        this.newItemInterface = newItemInterface;
        
    }

    public ChairPanel(NewItemInterface newItemInterface, Chair chair) {
        this(newItemInterface);
        this.chair = chair;
        this.chairTitle.setText("Editting a Chair");
        this.addToBasketButton.setText("Save Changes");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chairTitle = new javax.swing.JLabel();
        woodTypeLabel = new javax.swing.JLabel();
        woodTypeComboBox = new javax.swing.JComboBox<>();
        ArmrestsLabel = new javax.swing.JLabel();
        armrestsComboBox = new javax.swing.JComboBox<>();
        IDLabel = new javax.swing.JLabel();
        idNumberTextField = new javax.swing.JTextField();
        quantityLabel = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        addToBasketButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(57, 124, 213));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setPreferredSize(new java.awt.Dimension(450, 475));

        chairTitle.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        chairTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chairTitle.setText("Add a chair");

        woodTypeLabel.setText("Choose Wood Type");

        woodTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oak", "Walnut" }));

        ArmrestsLabel.setText("Add Armrests");

        armrestsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));

        IDLabel.setText("Add ID Number");

        idNumberTextField.setText("1");

        quantityLabel.setText("Choose Quantity");

        quantityTextField.setText("1");

        addToBasketButton.setText("Add To Basket");
        addToBasketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToBasketButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addToBasketButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ArmrestsLabel)
                                    .addComponent(armrestsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(quantityLabel)
                                        .addGap(0, 35, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chairTitle)
                                    .addComponent(woodTypeLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(166, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IDLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(woodTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(chairTitle)
                .addGap(38, 38, 38)
                .addComponent(woodTypeLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(quantityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(woodTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(ArmrestsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(armrestsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(IDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addToBasketButton)
                    .addComponent(idNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addToBasketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToBasketButtonActionPerformed
        // TODO add your handling code here:
        WoodType woodtype = WoodType.WALNUT;
        Armrests armrests = Armrests.NO;
        int quantity = 1;
        int idNumber = 1;
        try {
            if (this.woodTypeComboBox.getSelectedItem() == "Oak") {
                woodtype = WoodType.OAK;
            }
            if (this.armrestsComboBox.getSelectedItem() == "Yes") {
                armrests = Armrests.YES;
            }
            if (this.quantityTextField != null) {
                quantity = Integer.parseInt(this.quantityTextField.getText());
            }
            if (this.idNumberTextField != null) {
                idNumber = Integer.parseInt(this.idNumberTextField.getText());

            }
            Chair newChair = new Chair(armrests, woodtype, quantity, idNumber);
            
            if (chair == null){
                this.newItemInterface.newItemToBasket(newChair);
            }else{
                chair.setArms(armrests);
                chair.setIdNumber(idNumber);
                chair.setQuantity(quantity);
                chair.setWood(woodtype);
                this.newItemInterface.editItem(chair);
                JOptionPane.showMessageDialog(this, "Basket updated",
                    "Edit Complete",
                    JOptionPane.WARNING_MESSAGE);
                MainFrame.getInstance().clearDummy();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "This is an invalid character",
                    "WARNING",
                    JOptionPane.WARNING_MESSAGE);
            
        }
        //serializable lecture
    }//GEN-LAST:event_addToBasketButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArmrestsLabel;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JButton addToBasketButton;
    private javax.swing.JComboBox<String> armrestsComboBox;
    private javax.swing.JLabel chairTitle;
    private javax.swing.JTextField idNumberTextField;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JComboBox<String> woodTypeComboBox;
    private javax.swing.JLabel woodTypeLabel;
    // End of variables declaration//GEN-END:variables
}
