package GUI;

//
import Items.*;
import Interfaces.NewItemInterface;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import Items.Armrests;
import Items.WoodType;
import java.io.Serializable;

/**
 *
 * @author tomwi
 */
public class ChairPanel extends javax.swing.JPanel implements Serializable{

    private final NewItemInterface newItemInterface;
    private Chair chair;

    /**
     * Creates new form orderItemPanel
     *
     * @param newItemInterface
     */
    public ChairPanel(NewItemInterface newItemInterface) {
        initComponents();
        this.newItemInterface = newItemInterface;
        
    }

    public ChairPanel(NewItemInterface newItemInterface, Chair chair) {
        this(newItemInterface);
        this.chair = chair;
        this.chairTitle.setText("Editting a Chair");
        this.addToBasketButton.setText("Save Changes");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chairTitle = new javax.swing.JLabel();
        woodTypeLabel = new javax.swing.JLabel();
        woodTypeComboBox = new javax.swing.JComboBox();
        ArmrestsLabel = new javax.swing.JLabel();
        armrestsComboBox = new javax.swing.JComboBox();
        IDLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        addToBasketButton = new javax.swing.JButton();
        idFormattedTextField = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(57, 124, 213));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setPreferredSize(new java.awt.Dimension(450, 475));

        chairTitle.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        chairTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chairTitle.setText("Add a chair");

        woodTypeLabel.setText("Choose Wood Type");

        woodTypeComboBox.setModel(new DefaultComboBoxModel<>(WoodType.values())
        );
        woodTypeComboBox.setToolTipText("");

        ArmrestsLabel.setText("Add Armrests");

        armrestsComboBox.setModel(new DefaultComboBoxModel<>(Armrests.values()));

        IDLabel.setText("Add ID Number");

        quantityLabel.setText("Choose Quantity");

        quantityTextField.setText("1");

        addToBasketButton.setText("Add To Basket");
        addToBasketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToBasketButtonActionPerformed(evt);
            }
        });

        idFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        idFormattedTextField.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addToBasketButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ArmrestsLabel)
                                            .addComponent(armrestsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(72, 72, 72)
                                                .addComponent(quantityLabel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(102, 102, 102)
                                                .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(chairTitle)
                                    .addComponent(woodTypeLabel))
                                .addGap(0, 35, Short.MAX_VALUE)))
                        .addContainerGap(166, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDLabel)
                            .addComponent(woodTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(chairTitle)
                .addGap(38, 38, 38)
                .addComponent(woodTypeLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(quantityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(woodTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(ArmrestsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(armrestsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(IDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addToBasketButton)
                    .addComponent(idFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addToBasketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToBasketButtonActionPerformed
        // TODO add your handling code here:
        int quantity = 1;
        int idNumber = 1;
        
        try {
            Chair newChair = null;

            if (this.quantityTextField != null) {
                quantity = Integer.parseInt(this.quantityTextField.getText());
            }
            if (this.idFormattedTextField != null) {
                if(Integer.valueOf(idFormattedTextField.getText())>0){
                    idNumber = Integer.valueOf(idFormattedTextField.getText());
                    newChair = new Chair((Armrests)armrestsComboBox.getSelectedItem()
                            , (WoodType)woodTypeComboBox.getSelectedItem()
                            , quantity, idNumber);
                }
                while (Integer.valueOf(idFormattedTextField.getText())<0){
                    idFormattedTextField.setText(null);
                }
            }
            
            
            if (chair == null){
                this.newItemInterface.addNewItemToBasket(newChair);
            }else{
                chair.setArms((Armrests)armrestsComboBox.getSelectedItem());
                chair.setIdNumber(idNumber);
                chair.setQuantity(quantity);
                chair.setWood((WoodType)woodTypeComboBox.getSelectedItem());
                this.newItemInterface.editSingleItem(chair);
                JOptionPane.showMessageDialog(this, "Basket updated",
                    "Edit Complete",
                    JOptionPane.WARNING_MESSAGE);
                MainFrame.getInstance().clearInteractionPanel();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "This is an invalid character",
                    "WARNING",
                    JOptionPane.WARNING_MESSAGE);
            
        }
        //serializable lecture
        //swing formattedtextfields
        //numberformat
        //fieldformat
    }//GEN-LAST:event_addToBasketButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArmrestsLabel;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JButton addToBasketButton;
    private javax.swing.JComboBox armrestsComboBox;
    private javax.swing.JLabel chairTitle;
    private javax.swing.JFormattedTextField idFormattedTextField;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JComboBox woodTypeComboBox;
    private javax.swing.JLabel woodTypeLabel;
    // End of variables declaration//GEN-END:variables
}
