package GUI;

import Items.Desk;
import Items.WoodType;
import Interfaces.NewItemInterface;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tomwi
 */
public class DeskPanel extends javax.swing.JPanel {

    private final NewItemInterface newItemInterface;
    private Desk desk;

    /**
     * Creates new form DeskPanel
     *
     * @param newItemInterface
     */
    public DeskPanel(NewItemInterface newItemInterface) {
        initComponents();
        this.newItemInterface = newItemInterface;
    }
    public DeskPanel(NewItemInterface newItemInterface, Desk desk) {
        this(newItemInterface);
        this.desk = desk;
        this.deskTitle.setText("Editting a Desk");
        this.addToBasketButton.setText("Save Changes");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskTitle = new javax.swing.JLabel();
        woodTypeLabel = new javax.swing.JLabel();
        woodTypeComboBox = new javax.swing.JComboBox();
        drawerLabel = new javax.swing.JLabel();
        widthLabel = new javax.swing.JLabel();
        widthTextField = new javax.swing.JTextField();
        depthLabel = new javax.swing.JLabel();
        depthTextField = new javax.swing.JTextField();
        quantityLabel = new javax.swing.JLabel();
        addToBasketButton = new javax.swing.JButton();
        quantityTextField = new javax.swing.JTextField();
        drawersComboBox = new javax.swing.JComboBox<>();
        IdNumberLabel = new javax.swing.JLabel();
        idFormattedTextField = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(57, 124, 213));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setPreferredSize(new java.awt.Dimension(450, 475));

        deskTitle.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        deskTitle.setText("Add a Desk");

        woodTypeLabel.setText("Choose Wood Type");

        woodTypeComboBox.setModel(new DefaultComboBoxModel<>(WoodType.values()));

        drawerLabel.setText("Enter The amount of Drawers");

        widthLabel.setText("Choose the Width");

        widthTextField.setText("1");

        depthLabel.setText("Choose the Depth");

        depthTextField.setText("1");

        quantityLabel.setText("Choose Quantity");

        addToBasketButton.setText("Add to Basket");
        addToBasketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToBasketButtonActionPerformed(evt);
            }
        });

        quantityTextField.setText("1");

        drawersComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        IdNumberLabel.setText("Enter ID Number");

        idFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        idFormattedTextField.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addToBasketButton)
                .addGap(194, 194, 194))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drawerLabel)
                            .addComponent(widthLabel)
                            .addComponent(widthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(depthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drawersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantityLabel)
                            .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdNumberLabel)
                            .addComponent(idFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(depthLabel)
                    .addComponent(deskTitle)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(woodTypeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(woodTypeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(deskTitle)
                .addGap(40, 40, 40)
                .addComponent(woodTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(woodTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drawerLabel)
                    .addComponent(quantityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drawersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(widthLabel)
                    .addComponent(IdNumberLabel))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(widthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(depthLabel)
                .addGap(18, 18, 18)
                .addComponent(depthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addToBasketButton)
                .addContainerGap(102, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addToBasketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToBasketButtonActionPerformed

        int drawers = 1;
        double deskWidth = 1;
        double deskDepth = 1;
        int quantity = 1;
        int idNumber = 0;

        try {
            Desk newDesk = null;
            if (this.drawersComboBox != null) {
                drawers = Integer.parseInt(this.drawersComboBox.getSelectedItem().toString());
            }
            if (this.widthTextField != null) {
                deskWidth = Double.parseDouble(this.widthTextField.getText());
            }
            if (this.depthTextField != null) {
                deskDepth = Double.parseDouble(this.depthTextField.getText());
            }
            
            if (this.quantityTextField != null) {
                quantity = Integer.parseInt(this.quantityTextField.getText());
            }
            if (this.idFormattedTextField != null) {
                if(Integer.valueOf(idFormattedTextField.getText())>0){
                    idNumber = Integer.valueOf(idFormattedTextField.getText());
                    newDesk = new Desk(drawers, deskWidth, deskDepth, 
                    (WoodType)woodTypeComboBox.getSelectedItem(), 
                    quantity, idNumber);
                    
                }
                while (Integer.valueOf(idFormattedTextField.getText())<0){
                    idFormattedTextField.setText(null);
                }
            }
            
            
            if (desk == null){
                this.newItemInterface.newItemToBasket(newDesk);
            }else{
                desk.setDeskDepth(deskDepth);
                desk.setDeskWidth(deskWidth);
                desk.setDrawers(drawers);
                desk.setIdNumber(idNumber);
                desk.setQuantity(quantity);
                desk.setWood((WoodType)woodTypeComboBox.getSelectedItem());
                this.newItemInterface.editItem(desk);
                JOptionPane.showMessageDialog(this, "Basket updated",
                    "Edit Complete",
                    JOptionPane.WARNING_MESSAGE);
                MainFrame.getInstance().clearDummy();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "This is an invalid character",
                    "WARNING",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addToBasketButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdNumberLabel;
    private javax.swing.JButton addToBasketButton;
    private javax.swing.JLabel depthLabel;
    private javax.swing.JTextField depthTextField;
    private javax.swing.JLabel deskTitle;
    private javax.swing.JLabel drawerLabel;
    private javax.swing.JComboBox<String> drawersComboBox;
    private javax.swing.JFormattedTextField idFormattedTextField;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JLabel widthLabel;
    private javax.swing.JTextField widthTextField;
    private javax.swing.JComboBox woodTypeComboBox;
    private javax.swing.JLabel woodTypeLabel;
    // End of variables declaration//GEN-END:variables
}
