package GUI;

import Interfaces.ItemInterface;
import Interfaces.BasketInterface;
import Interfaces.SummaryInterface;
import Items.Chair;
import Items.Desk;
import Items.Table;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
/**
 *
 * @author tomwi
 */
public class MainFrame extends javax.swing.JFrame implements ItemInterface, BasketInterface, SummaryInterface{
    
    private final List<JPanel> forms = new ArrayList<>();
    private SummaryInterface summaryListener;
    private static MainFrame instance;
    /**
     * Creates new form RoflFrame
     */
    private MainFrame() {
        initComponents();
        initListeners();
    }

    public static MainFrame getInstance(){
        if (instance ==null){
            return instance = new MainFrame();
        }else{
            return instance;
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel1 = new GUI.ButtonPanel();
        titlePanel1 = new GUI.TitlePanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 32767));
        jPanel1 = new javax.swing.JPanel();
        dummyPanel = new javax.swing.JPanel();
        basketPanel1 = new GUI.BasketPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ROFC Ordering System");
        setBackground(new java.awt.Color(57, 124, 213));
        setForeground(new java.awt.Color(57, 124, 213));
        setSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));
        getContentPane().add(buttonPanel1, java.awt.BorderLayout.SOUTH);
        getContentPane().add(titlePanel1, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(filler1, java.awt.BorderLayout.LINE_START);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        dummyPanel.setBackground(new java.awt.Color(57, 124, 213));
        dummyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        dummyPanel.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(dummyPanel);
        jPanel1.add(basketPanel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initListeners() {
        buttonPanel1.addItemlListener(this);
        basketPanel1.addBasketListener(this);
        buttonPanel1.addBasketListener(this.basketPanel1);
        buttonPanel1.addItemlListener(this);
        buttonPanel1.addSummaryListener(this.basketPanel1);
        basketPanel1.addSummaryListener(this);
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            MainFrame.getInstance().setVisible(true);
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.BasketPanel basketPanel1;
    private GUI.ButtonPanel buttonPanel1;
    private javax.swing.JPanel dummyPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private GUI.TitlePanel titlePanel1;
    // End of variables declaration//GEN-END:variables


    

    @Override
    public void chairPanel() {
        dummyPanel.removeAll();         
        dummyPanel.add(new ChairPanel(basketPanel1));
        dummyPanel.updateUI();
        
    }
    @Override
    public void chairPanel(Chair chair) {
        dummyPanel.removeAll();         
        dummyPanel.add(new ChairPanel(basketPanel1, chair));
        dummyPanel.updateUI();      
    }
    
    @Override
    public void deskPanel() {
        dummyPanel.removeAll();         
        dummyPanel.add(new DeskPanel(basketPanel1));
        dummyPanel.updateUI();
        
    }
    
    @Override
    public void deskPanel(Desk desk) {
        dummyPanel.removeAll();         
        dummyPanel.add(new DeskPanel(basketPanel1, desk));
        dummyPanel.updateUI();
    }
    
    @Override
    public void tablePanel() {
        dummyPanel.removeAll();         
        dummyPanel.add(new TablePanel(basketPanel1));
        dummyPanel.updateUI();
        
    }
    
    @Override
    public void tablePanel(Table table) {
        dummyPanel.removeAll();         
        dummyPanel.add(new TablePanel(basketPanel1, table));
        dummyPanel.updateUI();
        
    }
    
    @Override
    public void summaryPanel(String summary){
        dummyPanel.removeAll();
        dummyPanel.add(new SummaryPanel(summary));
        dummyPanel.updateUI();
    }


    @Override
    public void removeAllItemsFromBasket() {
        basketPanel1.removeAll();
        basketPanel1.add(new BasketPanel());
        basketPanel1.updateUI();
    }

    @Override
    public void totalPricePanel() {
        dummyPanel.removeAll();
        TotalPricePanel pricePanel = new TotalPricePanel();
        pricePanel.setText("£" + String.valueOf(this.basketPanel1.totalPriceOfBasket()));
        dummyPanel.add(pricePanel);
        dummyPanel.updateUI();
        
    }
    
    @Override
    public void showBasketSummary() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void removeItem() {
        basketPanel1.removeAll();
        basketPanel1.add(new BasketPanel());
        basketPanel1.updateUI();
    }
    
    public void clearDummy(){
        
        dummyPanel.removeAll();
        dummyPanel.updateUI();
    }
}
